import type { Metadata, Viewport } from "next";
import { notFound } from "next/navigation";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getMessages, getTranslations, setRequestLocale } from "next-intl/server";
import { JsonLd } from "@/components/JsonLd";
import { RevealOnView } from "@/components/RevealOnView";
import { SmoothScrollOnAnchor } from "@/components/SmoothScrollOnAnchor";
import { site } from "@/lib/site";
import { routing } from "@/i18n/routing";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "Metadata" });
  const base = site.url;

  const isFr = locale === "fr";

  return {
    metadataBase: new URL(base),
    title: {
      default: t("title"),
      template: isFr
        ? `%s · Thomas Barthelemy — Développeur web à Alès`
        : `%s · Thomas Barthelemy — Web Developer in Alès`,
    },
    description: t("description"),
    keywords: isFr
      ? [
          "développeur web Alès",
          "création site internet Alès",
          "site web Alès",
          "agence web Alès",
          "développeur web Gard",
          "création site vitrine Alès",
          "refonte site web Alès",
          "freelance web Alès",
          "site internet Gard",
          "développeur web freelance Alès",
          "création site e-commerce Alès",
          "développeur WordPress Alès",
          "Thomas Barthelemy",
        ]
      : [
          "web developer Alès France",
          "freelance web developer France",
          "website creation France",
          "Next.js developer France",
          "Thomas Barthelemy",
        ],
    authors: [{ name: site.shortName, url: base }],
    creator: site.shortName,
    openGraph: {
      type: "website",
      locale: locale === "fr" ? "fr_FR" : "en_US",
      url: `${base}/${locale}`,
      siteName: site.shortName,
      title: t("title"),
      description: t("description"),
      // OG image is auto-generated by `app/[locale]/opengraph-image.tsx`.
    },
    twitter: {
      card: "summary_large_image",
      title: t("title"),
      description: t("description"),
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    icons: {
      icon: "/favicon.svg",
      // Apple touch icon is auto-generated by `app/apple-icon.tsx`.
    },
    alternates: {
      canonical: `${base}/${locale}`,
      languages: {
        fr: `${base}/fr`,
        en: `${base}/en`,
        "x-default": `${base}/${routing.defaultLocale}`,
      },
    },
  };
}

export const viewport: Viewport = {
  themeColor: "#05070f",
  colorScheme: "dark",
  width: "device-width",
  initialScale: 1,
};

// Namespaces actually consumed by client components (Nav, Projects, Contact,
// LanguageSwitcher). Server components use `getTranslations()` directly and do
// not need the messages shipped to the client.
const CLIENT_NAMESPACES = ["Nav", "Projects", "Contact", "LanguageSwitcher"] as const;

function pickNamespaces(messages: Record<string, unknown>) {
  const out: Record<string, unknown> = {};
  for (const ns of CLIENT_NAMESPACES) {
    if (ns in messages) out[ns] = messages[ns];
  }
  return out;
}

export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) notFound();

  setRequestLocale(locale);
  const messages = (await getMessages()) as Record<string, unknown>;
  const clientMessages = pickNamespaces(messages);

  return (
    <NextIntlClientProvider locale={locale} messages={clientMessages}>
      <JsonLd />
      <RevealOnView />
      <SmoothScrollOnAnchor />
      {children}
    </NextIntlClientProvider>
  );
}
